apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ghost-export-to-s3-chart.fullname" . }}
  labels:
    {{- include "ghost-export-to-s3-chart.labels" . | nindent 4 }}
data:
  GHOST_URL: "{{ .Values.ghost.apiBaseUrl }}"
  S3_DESTINATION: "{{ .Values.aws.s3.destination }}"
