apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost-export-to-s3.fullname" . }}
  labels:
    {{- include "ghost-export-to-s3.labels" . | nindent 4 }}
data:
  GHOST_AUTH_USERNAME: {{ default "" .Values.ghost.username | b64enc | quote }}
  GHOST_AUTH_PASSWORD: {{ default "" .Values.ghost.password | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ default "" .Values.aws.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY:  {{ default "" .Values.aws.secretKey | b64enc | quote }}
